trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Free Trial(90551aaf-c894-48b9-b16f-dbff2cefb986)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t 2048gameacr.azurecr.io/web-game:tag 2048-game
      az acr login -n 2048gameacr
      docker push 2048gameacr.azurecr.io/web-game:tag

- script: cat 01_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: '2048-k8s'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Free Trial(90551aaf-c894-48b9-b16f-dbff2cefb986)'
    azureContainerRegistry: '2048gameacr.azurecr.io'
    forceUpdate: false
